/* Generated By:JavaCC: Do not edit this line. LanguageTokensConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LanguageTokensConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Number = 1;
  /** RegularExpression Id. */
  int SmallLetter = 2;
  /** RegularExpression Id. */
  int CapitalLetter = 3;
  /** RegularExpression Id. */
  int Slash = 4;
  /** RegularExpression Id. */
  int Dott = 5;
  /** RegularExpression Id. */
  int Colon = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Number>",
    "<SmallLetter>",
    "<CapitalLetter>",
    "<Slash>",
    "<Dott>",
    "<Colon>",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\"",
    "\" \"",
  };

}
